// Generated by tools/fidelity_capture/generate_schema.py
pub const WORDS:usize=455;
pub const MASK_WORDS:usize=15;
pub const WIRE_BYTES:usize=1896;
pub fn observe(player:&eldenring::cs::PlayerIns)->Frame {
let mut out=Frame::default();
let chr=std::ptr::addr_of!(player.chr_ins);let owner=chr as usize;
let p=player.chr_ins.modules.physics.as_ptr();
let behavior=player.chr_ins.modules.behavior.as_ptr();
let tae=player.chr_ins.modules.time_act.as_ptr();
let event=player.chr_ins.modules.event.as_ptr();
let action=player.chr_ins.modules.action_request.as_ptr();
let behavior_data=player.chr_ins.modules.behavior_data.as_ptr();
let data=player.chr_ins.modules.data.as_ptr();
let fall=player.chr_ins.modules.fall.as_ptr();
let armor=player.chr_ins.modules.super_armor.as_ptr();
let toughness=player.chr_ins.modules.toughness.as_ptr();
let action_flag=player.chr_ins.modules.action_flag.as_ptr();
let ctrl=player.chr_ins.chr_ctrl.as_ptr();
let modifier=unsafe{read_pointer(std::ptr::addr_of!((*ctrl).modifier))}.unwrap_or(0) as *const eldenring::cs::ChrCtrlModifier;
let asm=player.chr_asm.as_ptr();let game_data=player.player_game_data.as_ptr();
// PhysicsTrack: no semantics guessed, raw bit patterns preserved.
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).position),0,4);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).last_update_position),4,4);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).interpolated_orientation),8,4);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).additional_rotation),12,4);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).orientation_euler),16,4);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).rotation_multiplier),20,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).motion_multiplier),21,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).gravity_multiplier),22,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).chr_push_up_factor),23,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).default_max_turn_rate),24,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).hit_height),25,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).hit_radius),26,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).weight),27,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).chr_proxy_pos_update_requested),28,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).standing_on_solid_ground),29,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).touching_solid_ground),30,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).is_falling),31,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).is_touching_ground),32,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).gravity_disabled),33,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).fade_out_gravity_disabled),34,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).flying_character_fall_requested),35,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).use_world_y_alignment_logic),36,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).is_surface_constrained),37,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).adjust_to_hi_collision),38,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).move_type_flags),39,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).physics_model_matrix),40,16);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).model_matrix),56,16);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).additional_orientation_quat),72,4);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).vertical_position_offset),76,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).scale_size_x),77,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).scale_size_y),78,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).scale_size_z),79,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).offset_y),80,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).ragdoll_revive_time),81,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).foot_ik_error_height_limit),82,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).disable_move),83,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).height_correction_request),84,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).chr_ragdoll_state),85,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).flags),86,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).flags_copy),87,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).chr_proxy_flags),88,1);} }
if owned(fall,owner) { unsafe{out.read(std::ptr::addr_of!((*fall).fall_timer),89,1);} }
if owned(fall,owner) { unsafe{out.read(std::ptr::addr_of!((*fall).force_max_fall_height),90,1);} }
if owned(fall,owner) { unsafe{out.read(std::ptr::addr_of!((*fall).disable_fall_motion),91,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).chr_hit_height),92,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).chr_hit_radius),93,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).step_disp_interpolate_time),94,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).step_disp_interpolate_trigger_value),95,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).is_enable_step_disp_interpolate),96,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).is_watcher_stones),97,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).physics_transform_matrix_squared),98,16);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).model_matrix_squared),114,16);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).foot_ik_error_on_gain),130,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).foot_ik_error_off_gain),131,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).forward_undulation_limit_radians),132,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).backward_undulation_limit_radians),133,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).side_undulation),134,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).undulation_correction_gain),135,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).weight_type),136,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).is_undulation),137,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).use_ik_normal_by_undulation),138,1);} }
if owned(ctrl,owner) { unsafe{out.read(std::ptr::addr_of!((*ctrl).hit_group_and_navimesh),139,1);} }

// AnimationTrack: no semantics guessed, raw bit patterns preserved.
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).read_idx),140,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).write_idx),141,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[0].anim_id),142,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[0].play_time),143,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[0].anim_length),144,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[1].anim_id),145,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[1].play_time),146,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[1].anim_length),147,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[2].anim_id),148,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[2].play_time),149,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[2].anim_length),150,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[3].anim_id),151,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[3].play_time),152,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[3].anim_length),153,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[4].anim_id),154,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[4].play_time),155,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[4].anim_length),156,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[5].anim_id),157,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[5].play_time),158,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[5].anim_length),159,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[6].anim_id),160,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[6].play_time),161,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[6].anim_length),162,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[7].anim_id),163,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[7].play_time),164,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[7].anim_length),165,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[8].anim_id),166,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[8].play_time),167,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[8].anim_length),168,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[9].anim_id),169,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[9].play_time),170,1);} }
if owned(tae,owner) { unsafe{out.read(std::ptr::addr_of!((*tae).anim_queue[9].anim_length),171,1);} }
if owned(behavior,owner) { unsafe{out.read(std::ptr::addr_of!((*behavior).animation_speed),172,1);} }
if owned(behavior,owner) { unsafe{out.read(std::ptr::addr_of!((*behavior).max_ankle_pitch_angle_rad),173,1);} }
if owned(behavior,owner) { unsafe{out.read(std::ptr::addr_of!((*behavior).max_ankle_roll_angle_rad),174,1);} }
if owned(behavior,owner) { unsafe{out.read(std::ptr::addr_of!((*behavior).ground_touch_state),175,1);} }
if owned(behavior,owner) { unsafe{out.read(std::ptr::addr_of!((*behavior).root_motion),176,4);} }
if owned(event,owner) { unsafe{out.read(std::ptr::addr_of!((*event).request_animation_id),180,1);} }
if owned(event,owner) { unsafe{out.read(std::ptr::addr_of!((*event).idle_anim_id),181,1);} }
if owned(event,owner) { unsafe{out.read(std::ptr::addr_of!((*event).ez_state_request_ladder),182,1);} }
if owned(event,owner) { unsafe{out.read(std::ptr::addr_of!((*event).ez_state_request_ladder_output),183,1);} }
if owned(event,owner) { unsafe{out.read(std::ptr::addr_of!((*event).flags),184,1);} }

// ActionTrackRaw: no semantics guessed, raw bit patterns preserved.
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).action_requests),185,2);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).previous_action_requests),187,2);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).new_action_presses),189,2);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).released_actions),191,2);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).cancel_ready_actions),193,2);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).queued_action_inputs),195,2);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).disabled_action_inputs),197,2);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).possible_action_inputs),199,2);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).possible_action_cancels),201,2);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).prev_possible_action_inputs),203,2);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).readback_new_presses),205,2);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).readback_cancel_ready),207,2);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).readback_queued_inputs),209,2);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).readback_possible_inputs),211,2);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).readback_possible_cancels),213,2);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).npc_action_id),215,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).requested_gesture),216,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).readback_npc_action_id),217,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).queue_tae_id_override),218,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).action_request_queue.current_tae_id),219,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).tae_cancels),220,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).movement_request_flags),221,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).queue_mode_enabled),222,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).action_timers.r1),223,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).action_timers.r2),224,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).action_timers.l1),225,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).action_timers.l2),226,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).action_timers.action),227,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).action_timers.roll),228,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).action_timers.jump),229,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).action_timers.use_item),230,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).action_timers.switch_spell),231,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).action_timers.change_weapon_r),232,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).action_timers.change_weapon_l),233,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).action_timers.change_item),234,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).action_timers.r3),235,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).action_timers.l3),236,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).action_timers.touch_r),237,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).action_timers.touch_l),238,1);} }

// LocomotionBehaviorTrack: no semantics guessed, raw bit patterns preserved.
if owned(behavior_data,owner) { unsafe{out.read(std::ptr::addr_of!((*behavior_data).hks_root_motion_mult),239,1);} }
if owned(behavior_data,owner) { unsafe{out.read(std::ptr::addr_of!((*behavior_data).turn_speed),240,1);} }
if owned(behavior_data,owner) { unsafe{out.read(std::ptr::addr_of!((*behavior_data).hks_animation_speed_multiplier),241,1);} }
if owned(behavior_data,owner) { unsafe{out.read(std::ptr::addr_of!((*behavior_data).fixed_rotation_direction),242,1);} }
if owned(behavior_data,owner) { unsafe{out.read(std::ptr::addr_of!((*behavior_data).has_twist_modifier),243,1);} }
if owned(ctrl,owner)&&modifier_owned(modifier,ctrl as usize) { unsafe{out.read(std::ptr::addr_of!((*modifier).data.root_motion_reduction),244,1);} }
if owned(ctrl,owner)&&modifier_owned(modifier,ctrl as usize) { unsafe{out.read(std::ptr::addr_of!((*modifier).data.movement_limit),245,1);} }
if owned(ctrl,owner)&&modifier_owned(modifier,ctrl as usize) { unsafe{out.read(std::ptr::addr_of!((*modifier).data.action_flags),246,1);} }
if owned(ctrl,owner)&&modifier_owned(modifier,ctrl as usize) { unsafe{out.read(std::ptr::addr_of!((*modifier).data.hks_flags),247,1);} }
if owned(action,owner) { unsafe{out.read(std::ptr::addr_of!((*action).movement_request_duration),248,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).material_info.normal_vector),249,4);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).material_info.orientation_matrix),253,16);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).material_info.hit_material),269,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).material_info.is_slippery_surface),270,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).material_info.is_non_slippery_surface),271,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).slide_info.slide_vector),272,4);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).slide_info.normal_angle),276,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).slide_info.normal_angle_deg),277,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).slide_info.is_sliding),278,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).slide_info.enable_angle_check),279,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).slide_info.enabled),280,1);} }
if owned(p,owner) { unsafe{out.read(std::ptr::addr_of!((*p).slide_info.enable_slide_interpolation),281,1);} }
if owned(behavior_data,owner) { unsafe{out.read(std::ptr::addr_of!((*behavior_data).min_twist_rank),282,1);} }

// EquipmentTrack: no semantics guessed, raw bit patterns preserved.
if true { unsafe{out.read(std::ptr::addr_of!((*asm).equipment_param_ids),283,22);} }
if true { unsafe{out.read(std::ptr::addr_of!((*asm).equipment.selected_slots.left_weapon_slot),305,1);} }
if true { unsafe{out.read(std::ptr::addr_of!((*asm).equipment.selected_slots.right_weapon_slot),306,1);} }
if true { unsafe{out.read(std::ptr::addr_of!((*asm).equipment.selected_slots.left_arrow_slot),307,1);} }
if true { unsafe{out.read(std::ptr::addr_of!((*asm).equipment.selected_slots.right_arrow_slot),308,1);} }
if true { unsafe{out.read(std::ptr::addr_of!((*asm).equipment.selected_slots.left_bolt_slot),309,1);} }
if true { unsafe{out.read(std::ptr::addr_of!((*asm).equipment.selected_slots.right_bolt_slot),310,1);} }
if true { unsafe{out.read(std::ptr::addr_of!((*asm).equipment.arm_style),311,1);} }

// AppearanceTrack: no semantics guessed, raw bit patterns preserved.
if true { unsafe{out.read(std::ptr::addr_of!((*game_data).face_data.face_data_buffer),312,72);} }
if true { unsafe{out.read(std::ptr::addr_of!((*game_data).gender),384,1);} }
if true { unsafe{out.read(std::ptr::addr_of!((*game_data).archetype),385,1);} }

// GameplayStateTrack: no semantics guessed, raw bit patterns preserved.
if owned(data,owner) { unsafe{out.read(std::ptr::addr_of!((*data).hp),386,1);} }
if owned(data,owner) { unsafe{out.read(std::ptr::addr_of!((*data).max_hp),387,1);} }
if owned(data,owner) { unsafe{out.read(std::ptr::addr_of!((*data).max_uncapped_hp),388,1);} }
if owned(data,owner) { unsafe{out.read(std::ptr::addr_of!((*data).base_hp),389,1);} }
if owned(data,owner) { unsafe{out.read(std::ptr::addr_of!((*data).fp),390,1);} }
if owned(data,owner) { unsafe{out.read(std::ptr::addr_of!((*data).max_fp),391,1);} }
if owned(data,owner) { unsafe{out.read(std::ptr::addr_of!((*data).base_fp),392,1);} }
if owned(data,owner) { unsafe{out.read(std::ptr::addr_of!((*data).stamina),393,1);} }
if owned(data,owner) { unsafe{out.read(std::ptr::addr_of!((*data).max_stamina),394,1);} }
if owned(data,owner) { unsafe{out.read(std::ptr::addr_of!((*data).base_stamina),395,1);} }
if owned(data,owner) { unsafe{out.read(std::ptr::addr_of!((*data).chara_init_param_id),396,1);} }
if owned(data,owner) { unsafe{out.read(std::ptr::addr_of!((*data).recoverable_hp),397,1);} }
if owned(data,owner) { unsafe{out.read(std::ptr::addr_of!((*data).recoverable_hp_time),398,1);} }
if owned(armor,owner) { unsafe{out.read(std::ptr::addr_of!((*armor).sa_durability),399,1);} }
if owned(armor,owner) { unsafe{out.read(std::ptr::addr_of!((*armor).sa_durability_max),400,1);} }
if owned(armor,owner) { unsafe{out.read(std::ptr::addr_of!((*armor).recover_time),401,1);} }
if owned(armor,owner) { unsafe{out.read(std::ptr::addr_of!((*armor).poise_broken_state),402,1);} }
if owned(toughness,owner) { unsafe{out.read(std::ptr::addr_of!((*toughness).toughness),403,1);} }
if owned(toughness,owner) { unsafe{out.read(std::ptr::addr_of!((*toughness).toughness_max),404,1);} }
if owned(toughness,owner) { unsafe{out.read(std::ptr::addr_of!((*toughness).recover_time),405,1);} }
if true { unsafe{out.read(std::ptr::addr_of!((*chr).stamina_recovery_remainder),406,1);} }
if true { unsafe{out.read(std::ptr::addr_of!((*chr).stamina_recovery_modifier),407,1);} }
if owned(data,owner) { unsafe{out.read(std::ptr::addr_of!((*data).draw_params),408,1);} }
if owned(data,owner) { unsafe{out.read(std::ptr::addr_of!((*data).block_id_origin),409,1);} }
if owned(toughness,owner) { unsafe{out.read(std::ptr::addr_of!((*toughness).trigger_max_toughness_update),410,1);} }

// EffectSignalsTrack: no semantics guessed, raw bit patterns preserved.
if true { unsafe{out.read(std::ptr::addr_of!((*chr).item_use_cast_sfx_id),411,1);} }
if true { unsafe{out.read(std::ptr::addr_of!((*chr).item_use_fire_sfx_id),412,1);} }
if true { unsafe{out.read(std::ptr::addr_of!((*chr).item_use_effect_sfx_id),413,1);} }
if true { unsafe{out.read(std::ptr::addr_of!((*chr).tae_queued_use_item),414,1);} }

// CombatStateTrack: no semantics guessed, raw bit patterns preserved.
if true { unsafe{out.read(std::ptr::addr_of!((*chr).is_locked_on),415,1);} }
if true { unsafe{out.read(std::ptr::addr_of!((*chr).lock_on_target_position),416,4);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).animation_action_flags),420,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).action_modifiers_flags),421,2);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).damage_level),423,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).guard_level),424,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).received_damage_type),425,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).turn_speed),426,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).lock_on_turn_speed),427,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).joint_turn_speed),428,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).facing_angle_correction_rad),429,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).root_motion_div),430,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).root_motion_mult_min_dist),431,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).speed_default),432,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).speed_extra),433,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).speed_boost),434,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).root_motion_mult_target_radius),435,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).disable_lock_on_angle),436,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).mov_dist_multiplier),437,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).cam_turn_dist_multiplier),438,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).ladder_dist_multiplier),439,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).sa_durability_multiplier),440,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).knockback_value),441,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).camera_lock_on_param_id),442,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).guard_behavior_judge_id),443,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).action_flags),444,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).weapon_model_location_overridden),445,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).sp_effect_wet_condition_depth),446,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).bullet_aim_angle_up_limit),447,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).bullet_aim_angle_down_limit),448,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).bullet_aim_angle_right_limit),449,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).bullet_aim_angle_left_limit),450,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).bullet_aim_angle_up_dead_zone),451,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).bullet_aim_angle_down_dead_zone),452,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).bullet_aim_angle_right_dead_zone),453,1);} }
if owned(action_flag,owner) { unsafe{out.read(std::ptr::addr_of!((*action_flag).bullet_aim_angle_left_dead_zone),454,1);} }

out
}
pub fn layout_report()->String {let mut out=String::new();
out.push_str(&format!("FIELD 5 position CSChrPhysicsModule.position offset=0x{:X} words=4 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,position)));
out.push_str(&format!("FIELD 5 last_update_position CSChrPhysicsModule.last_update_position offset=0x{:X} words=4 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,last_update_position)));
out.push_str(&format!("FIELD 5 interpolated_orientation CSChrPhysicsModule.interpolated_orientation offset=0x{:X} words=4 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,interpolated_orientation)));
out.push_str(&format!("FIELD 5 additional_rotation CSChrPhysicsModule.additional_rotation offset=0x{:X} words=4 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,additional_rotation)));
out.push_str(&format!("FIELD 5 orientation_euler CSChrPhysicsModule.orientation_euler offset=0x{:X} words=4 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,orientation_euler)));
out.push_str(&format!("FIELD 5 rotation_multiplier CSChrPhysicsModule.rotation_multiplier offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,rotation_multiplier)));
out.push_str(&format!("FIELD 5 motion_multiplier CSChrPhysicsModule.motion_multiplier offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,motion_multiplier)));
out.push_str(&format!("FIELD 5 gravity_multiplier CSChrPhysicsModule.gravity_multiplier offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,gravity_multiplier)));
out.push_str(&format!("FIELD 5 chr_push_up_factor CSChrPhysicsModule.chr_push_up_factor offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,chr_push_up_factor)));
out.push_str(&format!("FIELD 5 default_max_turn_rate CSChrPhysicsModule.default_max_turn_rate offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,default_max_turn_rate)));
out.push_str(&format!("FIELD 5 hit_height CSChrPhysicsModule.hit_height offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,hit_height)));
out.push_str(&format!("FIELD 5 hit_radius CSChrPhysicsModule.hit_radius offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,hit_radius)));
out.push_str(&format!("FIELD 5 weight CSChrPhysicsModule.weight offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,weight)));
out.push_str(&format!("FIELD 5 chr_proxy_pos_update_requested CSChrPhysicsModule.chr_proxy_pos_update_requested offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,chr_proxy_pos_update_requested)));
out.push_str(&format!("FIELD 5 standing_on_solid_ground CSChrPhysicsModule.standing_on_solid_ground offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,standing_on_solid_ground)));
out.push_str(&format!("FIELD 5 touching_solid_ground CSChrPhysicsModule.touching_solid_ground offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,touching_solid_ground)));
out.push_str(&format!("FIELD 5 is_falling CSChrPhysicsModule.is_falling offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,is_falling)));
out.push_str(&format!("FIELD 5 is_touching_ground CSChrPhysicsModule.is_touching_ground offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,is_touching_ground)));
out.push_str(&format!("FIELD 5 gravity_disabled CSChrPhysicsModule.gravity_disabled offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,gravity_disabled)));
out.push_str(&format!("FIELD 5 fade_out_gravity_disabled CSChrPhysicsModule.fade_out_gravity_disabled offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,fade_out_gravity_disabled)));
out.push_str(&format!("FIELD 5 flying_character_fall_requested CSChrPhysicsModule.flying_character_fall_requested offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,flying_character_fall_requested)));
out.push_str(&format!("FIELD 5 use_world_y_alignment_logic CSChrPhysicsModule.use_world_y_alignment_logic offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,use_world_y_alignment_logic)));
out.push_str(&format!("FIELD 5 is_surface_constrained CSChrPhysicsModule.is_surface_constrained offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,is_surface_constrained)));
out.push_str(&format!("FIELD 5 adjust_to_hi_collision CSChrPhysicsModule.adjust_to_hi_collision offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,adjust_to_hi_collision)));
out.push_str(&format!("FIELD 5 move_type_flags CSChrPhysicsModule.move_type_flags offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,move_type_flags)));
out.push_str(&format!("FIELD 5 physics_model_matrix ChrCtrl.physics_model_matrix offset=0x{:X} words=16 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,physics_model_matrix)));
out.push_str(&format!("FIELD 5 model_matrix ChrCtrl.model_matrix offset=0x{:X} words=16 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,model_matrix)));
out.push_str(&format!("FIELD 5 additional_orientation_quat ChrCtrl.additional_orientation_quat offset=0x{:X} words=4 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,additional_orientation_quat)));
out.push_str(&format!("FIELD 5 vertical_position_offset ChrCtrl.vertical_position_offset offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,vertical_position_offset)));
out.push_str(&format!("FIELD 5 scale_size_x ChrCtrl.scale_size_x offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,scale_size_x)));
out.push_str(&format!("FIELD 5 scale_size_y ChrCtrl.scale_size_y offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,scale_size_y)));
out.push_str(&format!("FIELD 5 scale_size_z ChrCtrl.scale_size_z offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,scale_size_z)));
out.push_str(&format!("FIELD 5 offset_y ChrCtrl.offset_y offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,offset_y)));
out.push_str(&format!("FIELD 5 ragdoll_revive_time ChrCtrl.ragdoll_revive_time offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,ragdoll_revive_time)));
out.push_str(&format!("FIELD 5 foot_ik_error_height_limit ChrCtrl.foot_ik_error_height_limit offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,foot_ik_error_height_limit)));
out.push_str(&format!("FIELD 5 disable_move ChrCtrl.disable_move offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,disable_move)));
out.push_str(&format!("FIELD 5 height_correction_request ChrCtrl.height_correction_request offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,height_correction_request)));
out.push_str(&format!("FIELD 5 chr_ragdoll_state ChrCtrl.chr_ragdoll_state offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,chr_ragdoll_state)));
out.push_str(&format!("FIELD 5 flags ChrCtrl.flags offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,flags)));
out.push_str(&format!("FIELD 5 flags_copy ChrCtrl.flags_copy offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,flags_copy)));
out.push_str(&format!("FIELD 5 chr_proxy_flags ChrCtrl.chr_proxy_flags offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,chr_proxy_flags)));
out.push_str(&format!("FIELD 5 fall_timer CSChrFallModule.fall_timer offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrFallModule,fall_timer)));
out.push_str(&format!("FIELD 5 force_max_fall_height CSChrFallModule.force_max_fall_height offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrFallModule,force_max_fall_height)));
out.push_str(&format!("FIELD 5 disable_fall_motion CSChrFallModule.disable_fall_motion offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrFallModule,disable_fall_motion)));
out.push_str(&format!("FIELD 5 chr_hit_height CSChrPhysicsModule.chr_hit_height offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,chr_hit_height)));
out.push_str(&format!("FIELD 5 chr_hit_radius CSChrPhysicsModule.chr_hit_radius offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,chr_hit_radius)));
out.push_str(&format!("FIELD 5 step_disp_interpolate_time CSChrPhysicsModule.step_disp_interpolate_time offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,step_disp_interpolate_time)));
out.push_str(&format!("FIELD 5 step_disp_interpolate_trigger_value CSChrPhysicsModule.step_disp_interpolate_trigger_value offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,step_disp_interpolate_trigger_value)));
out.push_str(&format!("FIELD 5 is_enable_step_disp_interpolate CSChrPhysicsModule.is_enable_step_disp_interpolate offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,is_enable_step_disp_interpolate)));
out.push_str(&format!("FIELD 5 is_watcher_stones CSChrPhysicsModule.is_watcher_stones offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,is_watcher_stones)));
out.push_str(&format!("FIELD 5 physics_transform_matrix_squared ChrCtrl.physics_transform_matrix_squared offset=0x{:X} words=16 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,physics_transform_matrix_squared)));
out.push_str(&format!("FIELD 5 model_matrix_squared ChrCtrl.model_matrix_squared offset=0x{:X} words=16 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,model_matrix_squared)));
out.push_str(&format!("FIELD 5 foot_ik_error_on_gain ChrCtrl.foot_ik_error_on_gain offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,foot_ik_error_on_gain)));
out.push_str(&format!("FIELD 5 foot_ik_error_off_gain ChrCtrl.foot_ik_error_off_gain offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,foot_ik_error_off_gain)));
out.push_str(&format!("FIELD 5 forward_undulation_limit_radians ChrCtrl.forward_undulation_limit_radians offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,forward_undulation_limit_radians)));
out.push_str(&format!("FIELD 5 backward_undulation_limit_radians ChrCtrl.backward_undulation_limit_radians offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,backward_undulation_limit_radians)));
out.push_str(&format!("FIELD 5 side_undulation ChrCtrl.side_undulation offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,side_undulation)));
out.push_str(&format!("FIELD 5 undulation_correction_gain ChrCtrl.undulation_correction_gain offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,undulation_correction_gain)));
out.push_str(&format!("FIELD 5 weight_type ChrCtrl.weight_type offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,weight_type)));
out.push_str(&format!("FIELD 5 is_undulation ChrCtrl.is_undulation offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,is_undulation)));
out.push_str(&format!("FIELD 5 use_ik_normal_by_undulation ChrCtrl.use_ik_normal_by_undulation offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,use_ik_normal_by_undulation)));
out.push_str(&format!("FIELD 5 hit_group_and_navimesh ChrCtrl.hit_group_and_navimesh offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrl,hit_group_and_navimesh)));
out.push_str(&format!("FIELD 6 read_idx CSChrTimeActModule.read_idx offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,read_idx)));
out.push_str(&format!("FIELD 6 write_idx CSChrTimeActModule.write_idx offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,write_idx)));
out.push_str(&format!("FIELD 6 queue_0_anim_id CSChrTimeActModule.anim_queue[0].anim_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+0*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_id)));
out.push_str(&format!("FIELD 6 queue_0_play_time CSChrTimeActModule.anim_queue[0].play_time offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+0*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,play_time)));
out.push_str(&format!("FIELD 6 queue_0_anim_length CSChrTimeActModule.anim_queue[0].anim_length offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+0*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_length)));
out.push_str(&format!("FIELD 6 queue_1_anim_id CSChrTimeActModule.anim_queue[1].anim_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+1*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_id)));
out.push_str(&format!("FIELD 6 queue_1_play_time CSChrTimeActModule.anim_queue[1].play_time offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+1*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,play_time)));
out.push_str(&format!("FIELD 6 queue_1_anim_length CSChrTimeActModule.anim_queue[1].anim_length offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+1*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_length)));
out.push_str(&format!("FIELD 6 queue_2_anim_id CSChrTimeActModule.anim_queue[2].anim_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+2*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_id)));
out.push_str(&format!("FIELD 6 queue_2_play_time CSChrTimeActModule.anim_queue[2].play_time offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+2*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,play_time)));
out.push_str(&format!("FIELD 6 queue_2_anim_length CSChrTimeActModule.anim_queue[2].anim_length offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+2*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_length)));
out.push_str(&format!("FIELD 6 queue_3_anim_id CSChrTimeActModule.anim_queue[3].anim_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+3*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_id)));
out.push_str(&format!("FIELD 6 queue_3_play_time CSChrTimeActModule.anim_queue[3].play_time offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+3*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,play_time)));
out.push_str(&format!("FIELD 6 queue_3_anim_length CSChrTimeActModule.anim_queue[3].anim_length offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+3*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_length)));
out.push_str(&format!("FIELD 6 queue_4_anim_id CSChrTimeActModule.anim_queue[4].anim_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+4*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_id)));
out.push_str(&format!("FIELD 6 queue_4_play_time CSChrTimeActModule.anim_queue[4].play_time offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+4*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,play_time)));
out.push_str(&format!("FIELD 6 queue_4_anim_length CSChrTimeActModule.anim_queue[4].anim_length offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+4*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_length)));
out.push_str(&format!("FIELD 6 queue_5_anim_id CSChrTimeActModule.anim_queue[5].anim_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+5*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_id)));
out.push_str(&format!("FIELD 6 queue_5_play_time CSChrTimeActModule.anim_queue[5].play_time offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+5*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,play_time)));
out.push_str(&format!("FIELD 6 queue_5_anim_length CSChrTimeActModule.anim_queue[5].anim_length offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+5*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_length)));
out.push_str(&format!("FIELD 6 queue_6_anim_id CSChrTimeActModule.anim_queue[6].anim_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+6*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_id)));
out.push_str(&format!("FIELD 6 queue_6_play_time CSChrTimeActModule.anim_queue[6].play_time offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+6*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,play_time)));
out.push_str(&format!("FIELD 6 queue_6_anim_length CSChrTimeActModule.anim_queue[6].anim_length offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+6*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_length)));
out.push_str(&format!("FIELD 6 queue_7_anim_id CSChrTimeActModule.anim_queue[7].anim_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+7*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_id)));
out.push_str(&format!("FIELD 6 queue_7_play_time CSChrTimeActModule.anim_queue[7].play_time offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+7*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,play_time)));
out.push_str(&format!("FIELD 6 queue_7_anim_length CSChrTimeActModule.anim_queue[7].anim_length offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+7*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_length)));
out.push_str(&format!("FIELD 6 queue_8_anim_id CSChrTimeActModule.anim_queue[8].anim_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+8*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_id)));
out.push_str(&format!("FIELD 6 queue_8_play_time CSChrTimeActModule.anim_queue[8].play_time offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+8*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,play_time)));
out.push_str(&format!("FIELD 6 queue_8_anim_length CSChrTimeActModule.anim_queue[8].anim_length offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+8*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_length)));
out.push_str(&format!("FIELD 6 queue_9_anim_id CSChrTimeActModule.anim_queue[9].anim_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+9*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_id)));
out.push_str(&format!("FIELD 6 queue_9_play_time CSChrTimeActModule.anim_queue[9].play_time offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+9*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,play_time)));
out.push_str(&format!("FIELD 6 queue_9_anim_length CSChrTimeActModule.anim_queue[9].anim_length offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrTimeActModule,anim_queue)+9*std::mem::size_of::<eldenring::cs::CSChrTimeActModuleAnim>()+std::mem::offset_of!(eldenring::cs::CSChrTimeActModuleAnim,anim_length)));
out.push_str(&format!("FIELD 6 animation_speed CSChrBehaviorModule.animation_speed offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrBehaviorModule,animation_speed)));
out.push_str(&format!("FIELD 6 max_ankle_pitch_angle_rad CSChrBehaviorModule.max_ankle_pitch_angle_rad offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrBehaviorModule,max_ankle_pitch_angle_rad)));
out.push_str(&format!("FIELD 6 max_ankle_roll_angle_rad CSChrBehaviorModule.max_ankle_roll_angle_rad offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrBehaviorModule,max_ankle_roll_angle_rad)));
out.push_str(&format!("FIELD 6 ground_touch_state CSChrBehaviorModule.ground_touch_state offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrBehaviorModule,ground_touch_state)));
out.push_str(&format!("FIELD 6 root_motion CSChrBehaviorModule.root_motion offset=0x{:X} words=4 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrBehaviorModule,root_motion)));
out.push_str(&format!("FIELD 6 request_animation_id CSChrEventModule.request_animation_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrEventModule,request_animation_id)));
out.push_str(&format!("FIELD 6 idle_anim_id CSChrEventModule.idle_anim_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrEventModule,idle_anim_id)));
out.push_str(&format!("FIELD 6 ez_state_request_ladder CSChrEventModule.ez_state_request_ladder offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrEventModule,ez_state_request_ladder)));
out.push_str(&format!("FIELD 6 ez_state_request_ladder_output CSChrEventModule.ez_state_request_ladder_output offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrEventModule,ez_state_request_ladder_output)));
out.push_str(&format!("FIELD 6 flags CSChrEventModule.flags offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrEventModule,flags)));
out.push_str(&format!("FIELD 7 action_requests CSChrActionRequestModule.action_requests offset=0x{:X} words=2 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,action_requests)));
out.push_str(&format!("FIELD 7 previous_action_requests CSChrActionRequestModule.previous_action_requests offset=0x{:X} words=2 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,previous_action_requests)));
out.push_str(&format!("FIELD 7 new_action_presses CSChrActionRequestModule.new_action_presses offset=0x{:X} words=2 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,new_action_presses)));
out.push_str(&format!("FIELD 7 released_actions CSChrActionRequestModule.released_actions offset=0x{:X} words=2 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,released_actions)));
out.push_str(&format!("FIELD 7 cancel_ready_actions CSChrActionRequestModule.cancel_ready_actions offset=0x{:X} words=2 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,cancel_ready_actions)));
out.push_str(&format!("FIELD 7 queued_action_inputs CSChrActionRequestModule.queued_action_inputs offset=0x{:X} words=2 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,queued_action_inputs)));
out.push_str(&format!("FIELD 7 disabled_action_inputs CSChrActionRequestModule.disabled_action_inputs offset=0x{:X} words=2 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,disabled_action_inputs)));
out.push_str(&format!("FIELD 7 possible_action_inputs CSChrActionRequestModule.possible_action_inputs offset=0x{:X} words=2 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,possible_action_inputs)));
out.push_str(&format!("FIELD 7 possible_action_cancels CSChrActionRequestModule.possible_action_cancels offset=0x{:X} words=2 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,possible_action_cancels)));
out.push_str(&format!("FIELD 7 prev_possible_action_inputs CSChrActionRequestModule.prev_possible_action_inputs offset=0x{:X} words=2 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,prev_possible_action_inputs)));
out.push_str(&format!("FIELD 7 readback_new_presses CSChrActionRequestModule.readback_new_presses offset=0x{:X} words=2 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,readback_new_presses)));
out.push_str(&format!("FIELD 7 readback_cancel_ready CSChrActionRequestModule.readback_cancel_ready offset=0x{:X} words=2 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,readback_cancel_ready)));
out.push_str(&format!("FIELD 7 readback_queued_inputs CSChrActionRequestModule.readback_queued_inputs offset=0x{:X} words=2 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,readback_queued_inputs)));
out.push_str(&format!("FIELD 7 readback_possible_inputs CSChrActionRequestModule.readback_possible_inputs offset=0x{:X} words=2 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,readback_possible_inputs)));
out.push_str(&format!("FIELD 7 readback_possible_cancels CSChrActionRequestModule.readback_possible_cancels offset=0x{:X} words=2 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,readback_possible_cancels)));
out.push_str(&format!("FIELD 7 npc_action_id CSChrActionRequestModule.npc_action_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,npc_action_id)));
out.push_str(&format!("FIELD 7 requested_gesture CSChrActionRequestModule.requested_gesture offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,requested_gesture)));
out.push_str(&format!("FIELD 7 readback_npc_action_id CSChrActionRequestModule.readback_npc_action_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,readback_npc_action_id)));
out.push_str(&format!("FIELD 7 queue_tae_id_override CSChrActionRequestModule.queue_tae_id_override offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,queue_tae_id_override)));
out.push_str(&format!("FIELD 7 queue_current_tae_id CSChrActionRequestModule.action_request_queue.current_tae_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,action_request_queue.current_tae_id)));
out.push_str(&format!("FIELD 7 tae_cancels CSChrActionRequestModule.tae_cancels offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,tae_cancels)));
out.push_str(&format!("FIELD 7 movement_request_flags CSChrActionRequestModule.movement_request_flags offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,movement_request_flags)));
out.push_str(&format!("FIELD 7 queue_mode_enabled CSChrActionRequestModule.queue_mode_enabled offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,queue_mode_enabled)));
out.push_str(&format!("FIELD 7 timer_r1 CSChrActionRequestModule.action_timers.r1 offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,action_timers.r1)));
out.push_str(&format!("FIELD 7 timer_r2 CSChrActionRequestModule.action_timers.r2 offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,action_timers.r2)));
out.push_str(&format!("FIELD 7 timer_l1 CSChrActionRequestModule.action_timers.l1 offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,action_timers.l1)));
out.push_str(&format!("FIELD 7 timer_l2 CSChrActionRequestModule.action_timers.l2 offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,action_timers.l2)));
out.push_str(&format!("FIELD 7 timer_action CSChrActionRequestModule.action_timers.action offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,action_timers.action)));
out.push_str(&format!("FIELD 7 timer_roll CSChrActionRequestModule.action_timers.roll offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,action_timers.roll)));
out.push_str(&format!("FIELD 7 timer_jump CSChrActionRequestModule.action_timers.jump offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,action_timers.jump)));
out.push_str(&format!("FIELD 7 timer_use_item CSChrActionRequestModule.action_timers.use_item offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,action_timers.use_item)));
out.push_str(&format!("FIELD 7 timer_switch_spell CSChrActionRequestModule.action_timers.switch_spell offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,action_timers.switch_spell)));
out.push_str(&format!("FIELD 7 timer_change_weapon_r CSChrActionRequestModule.action_timers.change_weapon_r offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,action_timers.change_weapon_r)));
out.push_str(&format!("FIELD 7 timer_change_weapon_l CSChrActionRequestModule.action_timers.change_weapon_l offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,action_timers.change_weapon_l)));
out.push_str(&format!("FIELD 7 timer_change_item CSChrActionRequestModule.action_timers.change_item offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,action_timers.change_item)));
out.push_str(&format!("FIELD 7 timer_r3 CSChrActionRequestModule.action_timers.r3 offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,action_timers.r3)));
out.push_str(&format!("FIELD 7 timer_l3 CSChrActionRequestModule.action_timers.l3 offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,action_timers.l3)));
out.push_str(&format!("FIELD 7 timer_touch_r CSChrActionRequestModule.action_timers.touch_r offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,action_timers.touch_r)));
out.push_str(&format!("FIELD 7 timer_touch_l CSChrActionRequestModule.action_timers.touch_l offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,action_timers.touch_l)));
out.push_str(&format!("FIELD 8 hks_root_motion_mult CSChrBehaviorDataModule.hks_root_motion_mult offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrBehaviorDataModule,hks_root_motion_mult)));
out.push_str(&format!("FIELD 8 turn_speed CSChrBehaviorDataModule.turn_speed offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrBehaviorDataModule,turn_speed)));
out.push_str(&format!("FIELD 8 hks_animation_speed_multiplier CSChrBehaviorDataModule.hks_animation_speed_multiplier offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrBehaviorDataModule,hks_animation_speed_multiplier)));
out.push_str(&format!("FIELD 8 fixed_rotation_direction CSChrBehaviorDataModule.fixed_rotation_direction offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrBehaviorDataModule,fixed_rotation_direction)));
out.push_str(&format!("FIELD 8 has_twist_modifier CSChrBehaviorDataModule.has_twist_modifier offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrBehaviorDataModule,has_twist_modifier)));
out.push_str(&format!("FIELD 8 root_motion_reduction ChrCtrlModifier.data.root_motion_reduction offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrlModifier,data.root_motion_reduction)));
out.push_str(&format!("FIELD 8 movement_limit ChrCtrlModifier.data.movement_limit offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrlModifier,data.movement_limit)));
out.push_str(&format!("FIELD 8 action_flags ChrCtrlModifier.data.action_flags offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrlModifier,data.action_flags)));
out.push_str(&format!("FIELD 8 hks_flags ChrCtrlModifier.data.hks_flags offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrCtrlModifier,data.hks_flags)));
out.push_str(&format!("FIELD 8 movement_request_duration CSChrActionRequestModule.movement_request_duration offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionRequestModule,movement_request_duration)));
out.push_str(&format!("FIELD 8 normal_vector CSChrPhysicsModule.material_info.normal_vector offset=0x{:X} words=4 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,material_info.normal_vector)));
out.push_str(&format!("FIELD 8 orientation_matrix CSChrPhysicsModule.material_info.orientation_matrix offset=0x{:X} words=16 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,material_info.orientation_matrix)));
out.push_str(&format!("FIELD 8 hit_material CSChrPhysicsModule.material_info.hit_material offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,material_info.hit_material)));
out.push_str(&format!("FIELD 8 is_slippery_surface CSChrPhysicsModule.material_info.is_slippery_surface offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,material_info.is_slippery_surface)));
out.push_str(&format!("FIELD 8 is_non_slippery_surface CSChrPhysicsModule.material_info.is_non_slippery_surface offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,material_info.is_non_slippery_surface)));
out.push_str(&format!("FIELD 8 slide_vector CSChrPhysicsModule.slide_info.slide_vector offset=0x{:X} words=4 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,slide_info.slide_vector)));
out.push_str(&format!("FIELD 8 normal_angle CSChrPhysicsModule.slide_info.normal_angle offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,slide_info.normal_angle)));
out.push_str(&format!("FIELD 8 normal_angle_deg CSChrPhysicsModule.slide_info.normal_angle_deg offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,slide_info.normal_angle_deg)));
out.push_str(&format!("FIELD 8 is_sliding CSChrPhysicsModule.slide_info.is_sliding offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,slide_info.is_sliding)));
out.push_str(&format!("FIELD 8 enable_angle_check CSChrPhysicsModule.slide_info.enable_angle_check offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,slide_info.enable_angle_check)));
out.push_str(&format!("FIELD 8 enabled CSChrPhysicsModule.slide_info.enabled offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,slide_info.enabled)));
out.push_str(&format!("FIELD 8 enable_slide_interpolation CSChrPhysicsModule.slide_info.enable_slide_interpolation offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrPhysicsModule,slide_info.enable_slide_interpolation)));
out.push_str(&format!("FIELD 8 min_twist_rank CSChrBehaviorDataModule.min_twist_rank offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrBehaviorDataModule,min_twist_rank)));
out.push_str(&format!("FIELD 9 equipment_param_ids ChrAsm.equipment_param_ids offset=0x{:X} words=22 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrAsm,equipment_param_ids)));
out.push_str(&format!("FIELD 9 left_weapon_slot ChrAsm.equipment.selected_slots.left_weapon_slot offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrAsm,equipment.selected_slots.left_weapon_slot)));
out.push_str(&format!("FIELD 9 right_weapon_slot ChrAsm.equipment.selected_slots.right_weapon_slot offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrAsm,equipment.selected_slots.right_weapon_slot)));
out.push_str(&format!("FIELD 9 left_arrow_slot ChrAsm.equipment.selected_slots.left_arrow_slot offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrAsm,equipment.selected_slots.left_arrow_slot)));
out.push_str(&format!("FIELD 9 right_arrow_slot ChrAsm.equipment.selected_slots.right_arrow_slot offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrAsm,equipment.selected_slots.right_arrow_slot)));
out.push_str(&format!("FIELD 9 left_bolt_slot ChrAsm.equipment.selected_slots.left_bolt_slot offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrAsm,equipment.selected_slots.left_bolt_slot)));
out.push_str(&format!("FIELD 9 right_bolt_slot ChrAsm.equipment.selected_slots.right_bolt_slot offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrAsm,equipment.selected_slots.right_bolt_slot)));
out.push_str(&format!("FIELD 9 arm_style ChrAsm.equipment.arm_style offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrAsm,equipment.arm_style)));
out.push_str(&format!("FIELD 10 face_buffer PlayerGameData.face_data.face_data_buffer offset=0x{:X} words=72 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::PlayerGameData,face_data.face_data_buffer)));
out.push_str(&format!("FIELD 10 gender PlayerGameData.gender offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::PlayerGameData,gender)));
out.push_str(&format!("FIELD 10 archetype PlayerGameData.archetype offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::PlayerGameData,archetype)));
out.push_str(&format!("FIELD 11 hp CSChrDataModule.hp offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrDataModule,hp)));
out.push_str(&format!("FIELD 11 max_hp CSChrDataModule.max_hp offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrDataModule,max_hp)));
out.push_str(&format!("FIELD 11 max_uncapped_hp CSChrDataModule.max_uncapped_hp offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrDataModule,max_uncapped_hp)));
out.push_str(&format!("FIELD 11 base_hp CSChrDataModule.base_hp offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrDataModule,base_hp)));
out.push_str(&format!("FIELD 11 fp CSChrDataModule.fp offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrDataModule,fp)));
out.push_str(&format!("FIELD 11 max_fp CSChrDataModule.max_fp offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrDataModule,max_fp)));
out.push_str(&format!("FIELD 11 base_fp CSChrDataModule.base_fp offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrDataModule,base_fp)));
out.push_str(&format!("FIELD 11 stamina CSChrDataModule.stamina offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrDataModule,stamina)));
out.push_str(&format!("FIELD 11 max_stamina CSChrDataModule.max_stamina offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrDataModule,max_stamina)));
out.push_str(&format!("FIELD 11 base_stamina CSChrDataModule.base_stamina offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrDataModule,base_stamina)));
out.push_str(&format!("FIELD 11 chara_init_param_id CSChrDataModule.chara_init_param_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrDataModule,chara_init_param_id)));
out.push_str(&format!("FIELD 11 recoverable_hp CSChrDataModule.recoverable_hp offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrDataModule,recoverable_hp)));
out.push_str(&format!("FIELD 11 recoverable_hp_time CSChrDataModule.recoverable_hp_time offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrDataModule,recoverable_hp_time)));
out.push_str(&format!("FIELD 11 sa_durability CSChrSuperArmorModule.sa_durability offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrSuperArmorModule,sa_durability)));
out.push_str(&format!("FIELD 11 sa_durability_max CSChrSuperArmorModule.sa_durability_max offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrSuperArmorModule,sa_durability_max)));
out.push_str(&format!("FIELD 11 armor_recover_time CSChrSuperArmorModule.recover_time offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrSuperArmorModule,recover_time)));
out.push_str(&format!("FIELD 11 poise_broken_state CSChrSuperArmorModule.poise_broken_state offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrSuperArmorModule,poise_broken_state)));
out.push_str(&format!("FIELD 11 toughness CSChrToughnessModule.toughness offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrToughnessModule,toughness)));
out.push_str(&format!("FIELD 11 toughness_max CSChrToughnessModule.toughness_max offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrToughnessModule,toughness_max)));
out.push_str(&format!("FIELD 11 toughness_recover_time CSChrToughnessModule.recover_time offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrToughnessModule,recover_time)));
out.push_str(&format!("FIELD 11 stamina_recovery_remainder ChrIns.stamina_recovery_remainder offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrIns,stamina_recovery_remainder)));
out.push_str(&format!("FIELD 11 stamina_recovery_modifier ChrIns.stamina_recovery_modifier offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrIns,stamina_recovery_modifier)));
out.push_str(&format!("FIELD 11 draw_params CSChrDataModule.draw_params offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrDataModule,draw_params)));
out.push_str(&format!("FIELD 11 block_id_origin CSChrDataModule.block_id_origin offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrDataModule,block_id_origin)));
out.push_str(&format!("FIELD 11 trigger_max_toughness_update CSChrToughnessModule.trigger_max_toughness_update offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrToughnessModule,trigger_max_toughness_update)));
out.push_str(&format!("FIELD 12 item_use_cast_sfx_id ChrIns.item_use_cast_sfx_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrIns,item_use_cast_sfx_id)));
out.push_str(&format!("FIELD 12 item_use_fire_sfx_id ChrIns.item_use_fire_sfx_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrIns,item_use_fire_sfx_id)));
out.push_str(&format!("FIELD 12 item_use_effect_sfx_id ChrIns.item_use_effect_sfx_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrIns,item_use_effect_sfx_id)));
out.push_str(&format!("FIELD 12 tae_queued_use_item ChrIns.tae_queued_use_item offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrIns,tae_queued_use_item)));
out.push_str(&format!("FIELD 13 is_locked_on ChrIns.is_locked_on offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrIns,is_locked_on)));
out.push_str(&format!("FIELD 13 lock_on_target_position ChrIns.lock_on_target_position offset=0x{:X} words=4 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrIns,lock_on_target_position)));
out.push_str(&format!("FIELD 13 animation_action_flags CSChrActionFlagModule.animation_action_flags offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,animation_action_flags)));
out.push_str(&format!("FIELD 13 action_modifiers_flags CSChrActionFlagModule.action_modifiers_flags offset=0x{:X} words=2 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,action_modifiers_flags)));
out.push_str(&format!("FIELD 13 damage_level CSChrActionFlagModule.damage_level offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,damage_level)));
out.push_str(&format!("FIELD 13 guard_level CSChrActionFlagModule.guard_level offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,guard_level)));
out.push_str(&format!("FIELD 13 received_damage_type CSChrActionFlagModule.received_damage_type offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,received_damage_type)));
out.push_str(&format!("FIELD 13 turn_speed CSChrActionFlagModule.turn_speed offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,turn_speed)));
out.push_str(&format!("FIELD 13 lock_on_turn_speed CSChrActionFlagModule.lock_on_turn_speed offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,lock_on_turn_speed)));
out.push_str(&format!("FIELD 13 joint_turn_speed CSChrActionFlagModule.joint_turn_speed offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,joint_turn_speed)));
out.push_str(&format!("FIELD 13 facing_angle_correction_rad CSChrActionFlagModule.facing_angle_correction_rad offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,facing_angle_correction_rad)));
out.push_str(&format!("FIELD 13 root_motion_div CSChrActionFlagModule.root_motion_div offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,root_motion_div)));
out.push_str(&format!("FIELD 13 root_motion_mult_min_dist CSChrActionFlagModule.root_motion_mult_min_dist offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,root_motion_mult_min_dist)));
out.push_str(&format!("FIELD 13 speed_default CSChrActionFlagModule.speed_default offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,speed_default)));
out.push_str(&format!("FIELD 13 speed_extra CSChrActionFlagModule.speed_extra offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,speed_extra)));
out.push_str(&format!("FIELD 13 speed_boost CSChrActionFlagModule.speed_boost offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,speed_boost)));
out.push_str(&format!("FIELD 13 root_motion_mult_target_radius CSChrActionFlagModule.root_motion_mult_target_radius offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,root_motion_mult_target_radius)));
out.push_str(&format!("FIELD 13 disable_lock_on_angle CSChrActionFlagModule.disable_lock_on_angle offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,disable_lock_on_angle)));
out.push_str(&format!("FIELD 13 mov_dist_multiplier CSChrActionFlagModule.mov_dist_multiplier offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,mov_dist_multiplier)));
out.push_str(&format!("FIELD 13 cam_turn_dist_multiplier CSChrActionFlagModule.cam_turn_dist_multiplier offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,cam_turn_dist_multiplier)));
out.push_str(&format!("FIELD 13 ladder_dist_multiplier CSChrActionFlagModule.ladder_dist_multiplier offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,ladder_dist_multiplier)));
out.push_str(&format!("FIELD 13 sa_durability_multiplier CSChrActionFlagModule.sa_durability_multiplier offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,sa_durability_multiplier)));
out.push_str(&format!("FIELD 13 knockback_value CSChrActionFlagModule.knockback_value offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,knockback_value)));
out.push_str(&format!("FIELD 13 camera_lock_on_param_id CSChrActionFlagModule.camera_lock_on_param_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,camera_lock_on_param_id)));
out.push_str(&format!("FIELD 13 guard_behavior_judge_id CSChrActionFlagModule.guard_behavior_judge_id offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,guard_behavior_judge_id)));
out.push_str(&format!("FIELD 13 action_flags CSChrActionFlagModule.action_flags offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,action_flags)));
out.push_str(&format!("FIELD 13 weapon_model_location_overridden CSChrActionFlagModule.weapon_model_location_overridden offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,weapon_model_location_overridden)));
out.push_str(&format!("FIELD 13 sp_effect_wet_condition_depth CSChrActionFlagModule.sp_effect_wet_condition_depth offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,sp_effect_wet_condition_depth)));
out.push_str(&format!("FIELD 13 bullet_aim_angle_up_limit CSChrActionFlagModule.bullet_aim_angle_up_limit offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,bullet_aim_angle_up_limit)));
out.push_str(&format!("FIELD 13 bullet_aim_angle_down_limit CSChrActionFlagModule.bullet_aim_angle_down_limit offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,bullet_aim_angle_down_limit)));
out.push_str(&format!("FIELD 13 bullet_aim_angle_right_limit CSChrActionFlagModule.bullet_aim_angle_right_limit offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,bullet_aim_angle_right_limit)));
out.push_str(&format!("FIELD 13 bullet_aim_angle_left_limit CSChrActionFlagModule.bullet_aim_angle_left_limit offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,bullet_aim_angle_left_limit)));
out.push_str(&format!("FIELD 13 bullet_aim_angle_up_dead_zone CSChrActionFlagModule.bullet_aim_angle_up_dead_zone offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,bullet_aim_angle_up_dead_zone)));
out.push_str(&format!("FIELD 13 bullet_aim_angle_down_dead_zone CSChrActionFlagModule.bullet_aim_angle_down_dead_zone offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,bullet_aim_angle_down_dead_zone)));
out.push_str(&format!("FIELD 13 bullet_aim_angle_right_dead_zone CSChrActionFlagModule.bullet_aim_angle_right_dead_zone offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,bullet_aim_angle_right_dead_zone)));
out.push_str(&format!("FIELD 13 bullet_aim_angle_left_dead_zone CSChrActionFlagModule.bullet_aim_angle_left_dead_zone offset=0x{:X} words=1 confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::CSChrActionFlagModule,bullet_aim_angle_left_dead_zone)));
out.push_str(&format!("ROOT PlayerIns.chr_ins offset=0x{:X} confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::PlayerIns,chr_ins)));
out.push_str(&format!("ROOT PlayerIns.chr_asm offset=0x{:X} confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::PlayerIns,chr_asm)));
out.push_str(&format!("ROOT PlayerIns.player_game_data offset=0x{:X} confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::PlayerIns,player_game_data)));
out.push_str(&format!("ROOT ChrIns.chr_ctrl offset=0x{:X} confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrIns,chr_ctrl)));
out.push_str(&format!("ROOT ChrIns.modules offset=0x{:X} confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrIns,modules)));
out.push_str(&format!("ROOT ChrInsModuleContainer.physics offset=0x{:X} confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrInsModuleContainer,physics)));
out.push_str(&format!("ROOT ChrInsModuleContainer.behavior offset=0x{:X} confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrInsModuleContainer,behavior)));
out.push_str(&format!("ROOT ChrInsModuleContainer.time_act offset=0x{:X} confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrInsModuleContainer,time_act)));
out.push_str(&format!("ROOT ChrInsModuleContainer.event offset=0x{:X} confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrInsModuleContainer,event)));
out.push_str(&format!("ROOT ChrInsModuleContainer.action_request offset=0x{:X} confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrInsModuleContainer,action_request)));
out.push_str(&format!("ROOT ChrInsModuleContainer.behavior_data offset=0x{:X} confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrInsModuleContainer,behavior_data)));
out.push_str(&format!("ROOT ChrInsModuleContainer.data offset=0x{:X} confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrInsModuleContainer,data)));
out.push_str(&format!("ROOT ChrInsModuleContainer.fall offset=0x{:X} confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrInsModuleContainer,fall)));
out.push_str(&format!("ROOT ChrInsModuleContainer.super_armor offset=0x{:X} confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrInsModuleContainer,super_armor)));
out.push_str(&format!("ROOT ChrInsModuleContainer.toughness offset=0x{:X} confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrInsModuleContainer,toughness)));
out.push_str(&format!("ROOT ChrInsModuleContainer.action_flag offset=0x{:X} confidence=REFERENCE\n",std::mem::offset_of!(eldenring::cs::ChrInsModuleContainer,action_flag)));
out}
