"""Generate exact-target entrypoint guards from the SHA-verified local image.
No game code export beyond 16-byte binding fingerprints; no engine mutation.
"""
import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'ghidra_query'))
from research_query import Image,DEFAULT
RVAS=(0x703e30,0x7048e0,0x507e60,0x50efa0,0x50b340,0x4f1c10,
      0x3deec0,0xe78ca0,0x4f1ab0,0x3dec70,0x1ebc000,0xe775e0,
      0x6514f0,0x25f810,0x25f7e0,0x6f1ec0,0x6f2410,0x4e5440,
      0x1ebbcd0,0x6f1bb0,0x1ebbfc0,0x6f1f20,0x6f27f0,0xe1c010,0x3c12a0)
if __name__=='__main__':
    image=Image(DEFAULT.parent)
    output=Path(__file__).resolve().parents[2]/'native_ui/NativeGhostFingerprints.h'
    rows=['// Exact SHA-verified ER 2.7.0.0 binding fingerprints. Generated by ghost_fingerprints.py.',
          '#pragma once','#include <cstdint>',
          'struct NativeGhostFingerprint { uintptr_t rva; unsigned char bytes[16]; };',
          'inline constexpr NativeGhostFingerprint nativeGhostFingerprints[]{']
    for rva in RVAS:
        rows.append(' {0x%X,{%s}},'%(rva,','.join('0x%02X'%b for b in image.read(image.base+rva,16))))
    rows.append('};')
    output.write_text('\n'.join(rows)+'\n',encoding='utf-8')
    print('SHA verified; generated',len(RVAS),'entrypoint guards:',output)
