"""Compile the user-supplied FXR CSV snapshot into an attributed read-only catalog.
No network access, native offsets, or guessed names. Run from the repo root.
"""
import csv,json,hashlib
from pathlib import Path
source=Path('research/fxr_reference_sheet.csv')
rows=list(csv.DictReader(source.open(encoding='utf-8-sig',newline='')))
keys=['BND','RESOURCES','REFS','ORIGIN','COLOR','EFFECT BEHAVIOUR','USEFUL INFO']
entries={}
for row in rows:
    id=int(row['ID'])
    if id<=0 or id>0xffffffff or id in entries:raise ValueError(f'Invalid/duplicate ID {id}')
    entries[id]=[row[k].strip() for k in keys]
def literal(s):
    # JSON quotes compatible with C++ UTF-8 source, except backslash-u not needed.
    return json.dumps(s,ensure_ascii=False)
p=Path('native_ui/ParticleReferenceData.inc')
p.write_text('// Generated by tools/import_fxr_reference.py; do not edit.\n'
    '// Source: https://docs.google.com/spreadsheets/d/1gmUiSpJtxFFl0g04MWMIIs37W13Yjp-WUxtbyv99JIQ/edit?gid=866341224\n'
    '// Snapshot 2026-10-08, CSV SHA256 '+hashlib.sha256(source.read_bytes()).hexdigest()+'\n'
    +''.join('{'+str(id)+','+','.join(literal(v) for v in data)+'},\n' for id,data in sorted(entries.items())),encoding='utf-8')
print(f'{len(entries)} unique IDs; {sum(bool(v[5] or v[6]) for v in entries.values())} described; generated {p.stat().st_size} bytes')
